# Generated by Django 2.2.5 on 2019-11-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191028_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='logos/', verbose_name='Service logo'),
        ),
        migrations.AddField(
            model_name='service',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
    ]
