# Generated by Django 2.2.5 on 2019-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_rent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
