# Generated by Django 2.2.5 on 2019-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Waiting for approval', 'Waiting for approval'), ('Not approved', 'Not approved'), ('Approved', 'Approved'), ('Done', 'Done')], default='Waiting for approval', max_length=100),
        ),
    ]
