# Generated by Django 2.2.5 on 2019-11-13 16:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20191109_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'profession', 'verbose_name_plural': 'professions'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'rating', 'verbose_name_plural': 'ratings'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'rent', 'verbose_name_plural': 'rents'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='service.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Waiting for approval', 'Waiting for approval'), ('Not approved', 'Not approved'), ('Approved', 'Approved'), ('Done', 'Done')], default='Waiting for approval', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Profession', verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='logos/', verbose_name='Logo usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulica'),
        ),
    ]
