# Generated by Django 2.2.5 on 2019-11-13 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20191113_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Rodzaj usługi', 'verbose_name_plural': 'Rodzaje usług'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Ocena', 'verbose_name_plural': 'Oceny'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Wynajem', 'verbose_name_plural': 'Wynajmy'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Usługa', 'verbose_name_plural': 'usługi'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service.Service', verbose_name='Usługi'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='service.Service', verbose_name='Usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='service',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Profession', verbose_name='Rodzaj usługi'),
        ),
    ]
