# Generated by Django 2.2.5 on 2019-11-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20191113_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'rodzaj uługi', 'verbose_name_plural': 'rodzaje usług'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'ocena', 'verbose_name_plural': 'oceny'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'wynajem', 'verbose_name_plural': 'wynajmy'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'usługa', 'verbose_name_plural': 'usługi'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service.Service', verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='service.Service', verbose_name='Usługa'),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='service.Service', verbose_name='Usługa')),
            ],
        ),
    ]
