# Generated by Django 2.2.5 on 2019-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20191121_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total price'),
        ),
    ]
