# Generated by Django 2.2.8 on 2019-12-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
