# Generated by Django 2.2.8 on 2019-12-14 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_rent_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='account_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only digits are allowed.')], verbose_name='Account number'),
        ),
    ]
