# Generated by Django 2.2.8 on 2019-12-14 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_service_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='account_number',
            field=models.CharField(blank=True, max_length=26, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only digits are allowed.')], verbose_name='Account number'),
        ),
    ]
