# Generated by Django 2.2.8 on 2019-12-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20191214_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'order'},
        ),
    ]
